@echo off
REM Generated by `lab paper schedule`. One session's decision, in order.
REM Editing this by hand is fine; re-running the command overwrites it.
cd /d "C:\Users\Kevin\Documents\GitHub\strategy-lab"

REM Refresh bars first. The runner reads the parquet store, not a live feed,
REM so skipping this means deciding on yesterday's prices -- which the runner
REM now refuses to do rather than doing quietly.
"C:\Users\Kevin\Documents\GitHub\strategy-lab\.venv\Scripts\python.exe" -m lab.cli pull --source alpaca --tickers "AAPL,MSFT,NVDA,AMZN,GOOGL,META,AVGO,JPM,XOM,UNH,LLY,V,COST,HD,PG,JNJ,WMT,CVX,MRK,KO,SPY" ^
  --tf 1d --since 2026-04-27
if errorlevel 1 (
  echo pull failed; not trading on stale data
  exit /b 1
)

REM One decision for right now, then exit.
"C:\Users\Kevin\Documents\GitHub\strategy-lab\.venv\Scripts\python.exe" -m lab.cli paper start "C:\Users\Kevin\Documents\GitHub\strategy-lab\strategies\blend_tilt.py" --config "C:\Users\Kevin\Documents\GitHub\strategy-lab\cfg\blend_tilt.yaml" ^
  --broker alpaca --once
exit /b %errorlevel%
